name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can switch to 'windows-latest' or 'macos-latest' if needed
    
    steps:
      - uses: actions/checkout@v3  # Checkout the code from GitHub
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure Node.js v18 is used
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install  # Install the project dependencies
      - name: Run tests
        run: npm test  # Run Jest tests
